use_frameworks!

platform :ios, '8.0'

target 'ZGPageControl_Example' do
  pod 'ZGPageControl', :path => '../'
  pod 'Masonry'

  target 'ZGPageControl_Tests' do
    inherit! :search_paths

    
  end
end
